name: GoBuild

on:
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Build
        run: make build
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p my.build.keychain.pw my.build.keychain security default-keychain -s my.build.keychain
          security unlock-keychain -p my.build.keychain.pw my.build.keychain
          security import certificate.p12 -k my.build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k my.build.keychain.pw my.build.keychain
          /usr/bin/codesign --force -s 30F3E8CE4EB52DCF22BCFDF756EC21B8673EFBBC ./bin/mac/* -v
      - name: Test
        run: make test
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: make deploy
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cselo-${{ steps.vars.outputs.tag }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



